### PR TITLE
Fix panic caused by omitempty in an embedded struct

### PR DESCRIPTION
**Pull request by aryehlev**
Panic caused by omitempty in an embedded struct #391
and fix panic cause in #401

### CODE REVIEW

**Review by goccy — CHANGES_REQUESTED** [review]
Please add the test code found in this Issue. Also, vm.go is an auto-generated file, so if you want to modify it, please modify internal/cmd/generator and regenerate it .

**Comment by aryehlev** [comment]
@goccy  done!

**Comment by goccy** [comment]
This PR mentions #391, but is it correct to fix #401 ?
#391 cannot be fixed this way. Please correct the description.

**Comment by aryehlev** [comment]
@goccy would you like me to separate to 2 separate PR's?
i saw the comment on the issue, and i pushed a fix and hope i covered all types.

**Comment by goccy** [comment]
In the first place, in this operation, NextField and Next should refer to the same thing, so this fix is ​​incorrect. You should fix the compiler side.

**Comment by aryehlev** [comment]
ok, u know it better than me.
 so would u like me to remove the parts where i changed it to Next?

**Comment by orisano** [comment]
The root cause of #391 is not setting the correct NextField to a field in the embed structure.
opcode graph

In this test case, NextField should point to the same thing as Next, so there is no problem.
However, there are cases where this is not the case, such as slice.

```go
func TestIssue391(t *testing.T) {
	type A struct {
		X []int `json:"x,omitempty"`
	}
	type B struct {
		A
	}
	type C struct {
		B
	}
	b, err := json.Marshal(C{})
	if err != nil {
		t.Fatal(err)
	}
	if string(b) != "{}" {
		t.Errorf("unexpected json: %s", string(b))
	}
}
```
The graph for the above case is shown below.

opcode graph2

Do not transition to `code.Next` when StructHeadOmitEmptySlice.
We need to fix the compiler so that NextField is set correctly.

**Comment by goccy** [comment]
Thank you for your contribution !
This PR is closed because we merged this PR that solves the same issue.
https://github.com/goccy/go-json/pull/438

**Comment by aryehlev** [comment]
@goccy sounds good to me, thank you🙏

**Pull request closed without merging**
