### PR TITLE
Fix stream decoder for unicode char

### PR DESCRIPTION
**Pull request by goccy**
fix https://github.com/goccy/go-json/issues/214

### CODE REVIEW

**Comment by DasSkelett** [comment]
I think the cause for this one failing is that the `s.length`  calculation in `reset()` isn't correct, which makes the buffer slice that the reader should write new data into being of size 0 (1- final `nul` byte), which causes endlessly repeated calls to `read()`, doubling the buffer again and again...

https://github.com/goccy/go-json/blob/d4a64f8cde830a03a53cbda8a1a05a3818d928a4/decode_stream.go#L65
`s.length` is currently set to the size of the buffer, however a part of that buffer might be `nul` bytes (actually at least the final byte always is, and in the initial buffer all bytes are).
If I'm not mistaken, it too should be `s.length = s.length - s.cursor` instead (calculated before the `s.cursor = 0` line). Since the `s.buf` slice basically is downsized by `s.cursor` bytes prior, `s.length` should be decreased by the same amount.

**Comment by Gaudeamus** [comment]
FYI after the fix there is runtime error: slice bounds out of range [-1:] at decode_stream.go:79

**Comment by goccy** [comment]
@Gaudeamus
I have confirmed that the test code you showed in #214 passes. If reproducible, could you report it as a new issue ?
( Did you check on the master branch ? )

**Comment by Gaudeamus** [comment]
@goccy Yes I've tested master. Can't reproduce unfortunately, occurred once in 20 min test, same json doesn't reproduce the error either. So I have nothing to issue yet (. The idea was to check whether it could be obvious from your perspective.

**Pull request merged**
