### PR TITLE
Fix: Switch to lazy init() in decoder and encoder

### PR DESCRIPTION
**Pull request by toddtreece**
## Why

See: https://github.com/grafana/grafana/pull/78651 (edit: new PR https://github.com/grafana/grafana/pull/95969)

There is additional memory overhead in Grafana due the import of [go-json in Apache Arrow](https://github.com/apache/arrow/blob/0552217efa4ba0a1a1a7857a86c92278ecf129c8/go/internal/json/json.go#L25). It looks like this is caused by `init()` initializing global variables in the encoder and decoder.

Grafana uses Apache Arrow, but does not currently use Arrow's JSON encoding/decoding features, so it would be ideal if we could avoid the additional memory overhead until JSON encoding/decoding is used.

This shows the impact of rolling this out to a couple of our rolling release channels in a production cluster:

image

## What

Switch to lazy initialization of global variables in decoder and encoder.

### CODE REVIEW

**Comment by toddtreece** [comment]
@goccy i apologize for pinging you directly, but could you take a quick look at this one when you have a chance?

**Comment by goccy** [comment]
Thank you for your contribution ! I'm concerned about the performance overhead caused by deferred execution. Could you check how the benchmark results change before and after the modification ?

**Comment by toddtreece** [comment]
> Could you check how the benchmark results change before and after the modification?

@goccy the commands and results are below. i used a regex to exclude the benchmarks for the other json libraries.

i ran this on the `grafana/go-json` fork:

```
go test -bench="Benchmark(.*GoJson[a-zA-Z0-9]*|[a-zA-Z0-9]+)" -count=10 -timeout 30m | tee grafana.txt
```

and this on `goccy/go-json`:

```
go test -bench="Benchmark(.*GoJson[a-zA-Z0-9]*|[a-zA-Z0-9]+)" -count=10 -timeout 30m | tee goccy.txt
```

and then running `benchstat`:

```
benchstat goccy
```

output:
* [benchstat.txt](https://github.com/user-attachments/files/17782343/benchstat.txt)
* [goccy.txt](https://github.com/user-attachments/files/17782344/goccy.txt)
* [grafana.txt](https://github.com/user-attachments/files/17782345/grafana.txt)

**Review by ccoVeille — APPROVED** [review]

**Comment by ptodev** [comment]
Hi! I came across this issue in [Grafana Alloy](https://github.com/grafana/alloy/pull/2253) and in the [OpenTelemetry Collector](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36765). It causes lots of unnecessary memory allocations for users who don't use functionality related to `goccy/go-json` but run hundreds of instances of a collector.

Thank you @toddtreece for opening the PR and @goccy for reviewing it, fingers crossed that it can be merged soon🤞

**Comment by goccy** [comment]
I've reviewed everything, and the only reasonable optimizations were for `initEncoder` and `initDecoder`. I’m sorry, but the other changes involve processes that are called frequently or provide minimal optimization benefits, so they cannot be accepted.

**Review by goccy — CHANGES_REQUESTED** [review]
I've reviewed everything, and the only reasonable optimizations were for initEncoder and initDecoder. I’m sorry, but the other changes involve processes that are called frequently or provide minimal optimization benefits, so they cannot be accepted.

**Comment by ptodev** [comment]
Hi @goccy, thank you for reviewing. Do you know how much memory would be allocated if `init()` still does the optimisations you mentioned are essential? If it's just a few KB, then that might be ok.

I also wonder if an environment variable could be a way to toggle the lazy cache on and off? It could be on by default, but applications which are affected by the memory usage could make optimisations lazy by hardcoding an environment variable.

**Comment by goccy** [comment]
The memory-intensive processes can be improved with initDecoder and initEncoder, so I believe the objective can be achieved.

**Comment by toddtreece** [comment]
i will make the requested updates

**Comment by toddtreece** [comment]
@goccy i reverted the additional changes in [a119ee5](https://github.com/goccy/go-json/pull/490/commits/a119ee5a0a3b8c632e4c68a1491aa7e9933e0248)

**Review by goccy — APPROVED** [review]
LGTM 👍

**Pull request merged**
